"use strict";
let car = 'sabaru';
console.log("is car == 'sabaru'? i predict true");
console.log(car == 'sabaru');
console.log("is car !=='sabaru'? i predict true");
console.log(car !== 'sabaru');
console.log("is car == 'ford'? i predict true");
console.log(car == 'ford');
console.log("is car !=='ford'? i predict true");
console.log(car !== 'ford');
console.log("is car == 'suzuki'? i predict true");
console.log(car == 'suzuki');
console.log("is car !=='suzuki'? i predict true");
console.log(car !== 'suzuki');
console.log("is car == 'toyota'? i predict true");
console.log(car == 'toyota');
console.log("is car !== 'toyota'? i predict true");
console.log(car !== 'toyota');
console.log("is car == 'BMW'? i predict true");
console.log(car == 'BMW');
console.log("is car !== 'BMW'? i predict true");
console.log(car !== 'BMW');
